### ISSUE TITLE
Unexpected variant index: 182

### ISSUE THREAD

**Issue by MarioProjects** [samuelvanderwaal/metaplex_decoder_py#1]
Heyoo Samuel!

Thanks for your utilities, I really appreciate it. I am trying to use the decoder but getting an error.

When running:

```python
from metaplex_decoder import *
metadata = deserialize_metadata("DFtbQ8mvTwmycT4bTFK4xVCkYNMW2NKGTkaaPKGBze4c")
```

I get:

```bash
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: "Unexpected variant index: 182" }', src/lib.rs:21:65
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: "Unexpected variant index: 182" }

```

----------------------
Ubuntu 20.04
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux

**Comment by samuelvanderwaal** [comment]
This lib doesn't make a network request to get the data from Solana, it just decodes base58 account info into a Metadata struct. You can't just pass it a mint address you actually have to make the network call yourself to get the account info first.

**Comment by MarioProjects** [comment]
Thanks!
